#!/usr/bin/env python3
"""
Generate image manifest for PWA caching
Scans the images/ directory and creates a JSON manifest file
"""

import os
import json
from pathlib import Path

def generate_image_manifest():
    """Generate a JSON manifest of all images in the images/ directory"""
    
    # Define supported image extensions
    image_extensions = {'.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp', '.ico', '.bmp'}
    
    # Get the directory where this script is located
    script_dir = Path(__file__).parent
    images_dir = script_dir / 'images'
    
    # Check if images directory exists
    if not images_dir.exists():
        print(f"Images directory not found: {images_dir}")
        return
    
    # Collect all image files
    image_files = []
    
    for file_path in images_dir.iterdir():
        if file_path.is_file() and file_path.suffix.lower() in image_extensions:
            # Create relative path from web root (GitHub Pages subdirectory)
            relative_path = f"/web_workshop/images/{file_path.name}"
            image_files.append(relative_path)
    
    # Sort for consistent output
    image_files.sort()
    
    # Create manifest object
    manifest = {
        "images": image_files,
        "generated_at": "auto-generated by GitHub Actions",
        "total_images": len(image_files)
    }
    
    # Write manifest file
    manifest_path = script_dir / 'image-manifest.json'
    with open(manifest_path, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
    
    print(f"Generated manifest with {len(image_files)} images:")
    for img in image_files:
        print(f"  - {img}")
    
    return manifest

if __name__ == "__main__":
    manifest = generate_image_manifest()
    print(f"\nManifest saved to: image-manifest.json")