#!/usr/bin/env python3
"""
Generate resource manifest for PWA caching
Scans the images/ and resources/ directories and creates a JSON manifest file
"""

import os
import json
from pathlib import Path

def generate_resource_manifest():
    """Generate a JSON manifest of all resources in the images/ and resources/ directories"""
    
    # Define supported image extensions
    image_extensions = {'.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp', '.ico', '.bmp'}
    
    # Get the repo root (two levels up from resources/scripts/)
    repo_root = Path(__file__).parent.parent.parent
    resources_dir = repo_root / 'resources'
    images_dir = resources_dir / 'images'
    
    # Collect all image files (recursively, so category subfolders are included)
    image_files = []
    if images_dir.exists():
        for file_path in images_dir.rglob('*'):
            if file_path.is_file() and file_path.suffix.lower() in image_extensions:
                # Create relative path from web root (GitHub Pages subdirectory)
                rel = file_path.relative_to(images_dir).as_posix()
                relative_path = f"/web_workshop/resources/images/{rel}"
                image_files.append(relative_path)
    
    # Collect ALL resource files (no extension filtering)
    resource_files = []
    if resources_dir.exists():
        for file_path in resources_dir.rglob('*'):
            if file_path.is_file():
                # Skip dev-only / gitignored files so local runs match CI output
                if 'node_modules' in file_path.parts or file_path.name in ('package-lock.json', '.DS_Store'):
                    continue
                # Images are listed separately in the images array; don't duplicate them here
                if images_dir in file_path.parents:
                    continue
                # Create relative path from web root (GitHub Pages subdirectory)
                relative_path = f"/web_workshop/resources/{file_path.relative_to(resources_dir).as_posix()}"
                resource_files.append(relative_path)
    
    # Sort for consistent output
    image_files.sort()
    resource_files.sort()
    
    # Create manifest object
    manifest = {
        "generated_at": "auto-generated by GitHub Actions",
        "resources": resource_files,
        "images": image_files
    }

    # Write manifest file
    manifest_path = resources_dir / 'resource-manifest.json'
    with open(manifest_path, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, indent=2)
    
    print(f"Generated manifest with {len(image_files)} images and {len(resource_files)} resources:")
    for img in image_files:
        print(f"  - {img}")
    for res in resource_files:
        print(f"  - {res}")
    
    return manifest

if __name__ == "__main__":
    manifest = generate_resource_manifest()
    print(f"\nManifest saved to: resources/resource-manifest.json")